name: 'dbt_scr'
version: '1.0.0'
config-version: 2

profile: 'dbt_scr'

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  dbt_scr:
    staging:
      +materialized: view
    marts:
      +materialized: table